### PR TITLE
Developments from Xioaming

### PR DESCRIPTION
**Pull request by johannes-darms**

### CODE REVIEW

**Comment by johannes-darms** [comment]
can you please have a look and merge into main if you OK with the changes?

**Review by ReneHaensel — COMMENTED** [review]
seems to be legit

**Review by ChristophB — COMMENTED** [review]
I was unable to create a new NFDI4Health Resource on a fresh installation.

## Logs
```
fdi4health-lap-seek | I, [2022-07-01T11:02:56.289504 #104]  INFO -- : Can not save/submit because:
nfdi4health-lap-seek | I, [2022-07-01T11:02:56.289616 #104]  INFO -- : {}
nfdi4health-lap-seek | E, [2022-07-01T11:02:56.695904 #104] ERROR -- : ERROR - ActionView::Template::Error (Couldn't find Project with 'id'=2)
nfdi4health-lap-seek | E, [2022-07-01T11:02:56.696004 #104] ERROR -- : Sending execption ERROR - ActionView::Template::Error (Couldn't find Project with 'id'=2)
nfdi4health-lap-seek | I, [2022-07-01T11:02:56.699000 #104]  INFO -- : method=POST path=/studyhub_resources/new_resource format=html controller=StudyhubResourcesController action=new_resource status=500 duration=907.00 view=1.69 db=103.09 time=8427.63 user_agent=Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.115 Safari/537.36 OPR/88.0.4412.53
```

## Steps to reproduce
1. build image and start containers with docker-compose.yml from [lap-deployment](https://github.com/nfdi4health/lap-deployment)
2. open seek in browser and create a new account
3. navigate to `http://localhost:3000/studyhub_resources/new`, select "Study" and submit the form

**Comment by whomingbird** [comment]
According the MDS, there is no concept of the  "project".  Therefor I was asked to add all the resources to a default project. 
You can set up the default project with 

```
rails c
Loading development environment (Rails 5.2.4.6)
2.7.5 :001 > Seek::Config.nfdi_default_project_id = 1
 => 1
```
but it might be changed in the future if we introduce "project" to group the resource.

**Comment by ChristophB** [comment]
I see, so I have to modify the configs first.

I find this a bit contraintuitive. Wouldn't it be better to set `nfdi_default_project_id` to 1 in [config/seek/initializers/seek_configuration.rb](https://github.com/nfdi4health/seek/blob/9bf34d2f1ccf45b3d8f49649b3ce72c7eecf1f87/config/initializers/seek_configuration.rb#L267)? The error would be gone and one can still update the default ID if necessary.

**Comment by whomingbird** [comment]
yes, i agree. i can not remeber why it was set to 2.  Could you please change 
`nfdi_default_project_id. =1  in 
`  [config/seek/initializers/seek_configuration.rb](https://github.com/nfdi4health/seek/blob/9bf34d2f1ccf45b3d8f49649b3ce72c7eecf1f87/config/initializers/seek_configuration.rb#L267)

**Comment by ChristophB** [comment]
Done. :)
See: https://github.com/nfdi4health/seek/commit/47846001ed1331584941efaf939da2c12eaae75b.

**Comment by whomingbird** [comment]
Thanks!! i think i have a google doc to explain the steps how to set up a NFDI4health SEEK instance. But i can not open google docs and any google products in China.   :-(  Currently i am in the mandatory hotel quarantine.   Local time 21:34

**Pull request merged**
